/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitest;
import AppPackage.AnimationClass;
/**
 *
 * @author N7
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        DeployTrain = new javax.swing.JButton();
        PassengerSpinner = new javax.swing.JSpinner();
        CapacitySpinner = new javax.swing.JSpinner();
        Station = new javax.swing.JLabel();
        TrainCapacity = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        passenger_station_1 = new javax.swing.JToggleButton();
        passenger_station_2 = new javax.swing.JToggleButton();
        passenger_station_3 = new javax.swing.JToggleButton();
        passenger_station_4 = new javax.swing.JToggleButton();
        passenger_station_5 = new javax.swing.JToggleButton();
        passenger_station_6 = new javax.swing.JToggleButton();
        passenger_station_7 = new javax.swing.JToggleButton();
        passenger_station_8 = new javax.swing.JToggleButton();
        AddPassengers = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("BigNoodleTitling", 0, 24)); // NOI18N
        jTextField1.setText("1");
        jTextField1.setOpaque(false);
        jTextField1.setRequestFocusEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1177, 562));
        setResizable(false);
        getContentPane().setLayout(null);

        DeployTrain.setBackground(new java.awt.Color(255, 255, 255));
        DeployTrain.setFont(new java.awt.Font("BigNoodleTitling", 0, 36)); // NOI18N
        DeployTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/deploydefault.png"))); // NOI18N
        DeployTrain.setBorder(null);
        DeployTrain.setBorderPainted(false);
        DeployTrain.setContentAreaFilled(false);
        DeployTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeployTrainActionPerformed(evt);
            }
        });
        getContentPane().add(DeployTrain);
        DeployTrain.setBounds(1010, 440, 210, 90);

        PassengerSpinner.setFont(new java.awt.Font("BigNoodleTitling", 0, 24)); // NOI18N
        getContentPane().add(PassengerSpinner);
        PassengerSpinner.setBounds(510, 500, 70, 50);

        CapacitySpinner.setFont(new java.awt.Font("BigNoodleTitling", 0, 24)); // NOI18N
        getContentPane().add(CapacitySpinner);
        CapacitySpinner.setBounds(920, 460, 70, 50);

        Station.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/capacity.png"))); // NOI18N
        getContentPane().add(Station);
        Station.setBounds(700, 460, 240, 60);

        TrainCapacity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/station.png"))); // NOI18N
        getContentPane().add(TrainCapacity);
        TrainCapacity.setBounds(60, 426, 210, 74);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 170, 34, 14);

        passenger_station_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num1Stationdef.png"))); // NOI18N
        passenger_station_1.setBorderPainted(false);
        passenger_station_1.setContentAreaFilled(false);
        passenger_station_1.setFocusPainted(false);
        passenger_station_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_1ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_1);
        passenger_station_1.setBounds(240, 420, 50, 80);

        passenger_station_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num2Stationdef.png"))); // NOI18N
        passenger_station_2.setBorderPainted(false);
        passenger_station_2.setContentAreaFilled(false);
        passenger_station_2.setFocusPainted(false);
        passenger_station_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_2ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_2);
        passenger_station_2.setBounds(290, 420, 50, 80);

        passenger_station_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num3Stationdef.png"))); // NOI18N
        passenger_station_3.setBorderPainted(false);
        passenger_station_3.setContentAreaFilled(false);
        passenger_station_3.setFocusPainted(false);
        passenger_station_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_3ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_3);
        passenger_station_3.setBounds(340, 420, 50, 80);

        passenger_station_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num4Stationdef.png"))); // NOI18N
        passenger_station_4.setBorderPainted(false);
        passenger_station_4.setContentAreaFilled(false);
        passenger_station_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_4ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_4);
        passenger_station_4.setBounds(390, 410, 50, 100);

        passenger_station_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num5Stationdef.png"))); // NOI18N
        passenger_station_5.setBorderPainted(false);
        passenger_station_5.setContentAreaFilled(false);
        passenger_station_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_5ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_5);
        passenger_station_5.setBounds(440, 420, 50, 80);

        passenger_station_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num6Stationdef.png"))); // NOI18N
        passenger_station_6.setBorderPainted(false);
        passenger_station_6.setContentAreaFilled(false);
        passenger_station_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_6ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_6);
        passenger_station_6.setBounds(490, 420, 50, 80);

        passenger_station_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num7Stationdef.png"))); // NOI18N
        passenger_station_7.setBorderPainted(false);
        passenger_station_7.setContentAreaFilled(false);
        passenger_station_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_7ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_7);
        passenger_station_7.setBounds(540, 420, 50, 80);

        passenger_station_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/Num8Stationdef.png"))); // NOI18N
        passenger_station_8.setBorderPainted(false);
        passenger_station_8.setContentAreaFilled(false);
        passenger_station_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_station_8ActionPerformed(evt);
            }
        });
        getContentPane().add(passenger_station_8);
        passenger_station_8.setBounds(590, 420, 50, 80);

        AddPassengers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/addpass3.png"))); // NOI18N
        AddPassengers.setBorderPainted(false);
        AddPassengers.setContentAreaFilled(false);
        AddPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengersActionPerformed(evt);
            }
        });
        getContentPane().add(AddPassengers);
        AddPassengers.setBounds(260, 480, 257, 90);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/FINALBG2.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1330, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeployTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeployTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeployTrainActionPerformed

    private void passenger_station_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_1ActionPerformed

    private void passenger_station_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_4ActionPerformed

    private void passenger_station_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_5ActionPerformed

    private void passenger_station_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void passenger_station_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_6ActionPerformed

    private void passenger_station_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_2ActionPerformed

    private void passenger_station_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_3ActionPerformed

    private void passenger_station_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_station_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_station_7ActionPerformed

    private void AddPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPassengersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPassengers;
    private javax.swing.JLabel Background;
    private javax.swing.JSpinner CapacitySpinner;
    private javax.swing.JButton DeployTrain;
    private javax.swing.JSpinner PassengerSpinner;
    private javax.swing.JLabel Station;
    private javax.swing.JLabel TrainCapacity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton passenger_station_1;
    private javax.swing.JToggleButton passenger_station_2;
    private javax.swing.JToggleButton passenger_station_3;
    private javax.swing.JToggleButton passenger_station_4;
    private javax.swing.JToggleButton passenger_station_5;
    private javax.swing.JToggleButton passenger_station_6;
    private javax.swing.JToggleButton passenger_station_7;
    private javax.swing.JToggleButton passenger_station_8;
    // End of variables declaration//GEN-END:variables
}
